In [1]:
import numpy as np
list1 = [10,20,30,40,50]
array1 = np.array(list1)
print(array1)

[10 20 30 40 50]


In [16]:

list1 = [[10,20,30],[40,50,60],[70,80,90]]
array1 = np.array(list1)
print(array1)
type(array1)
array1.ndim
array1.shape

[[10 20 30]
 [40 50 60]
 [70 80 90]]


(3, 3)

In [17]:
array1=np.arange(1,8)
print(array1)
array1.size

[1 2 3 4 5 6 7]


7

In [18]:
array1 = np.arange(11,17).reshape((2,3))
print(array1)
array1.dtype

[[11 12 13]
 [14 15 16]]


dtype('int64')

In [19]:
array1 = np.zeros(4)
print(array1)
array1.dtype

[0. 0. 0. 0.]


dtype('float64')

In [13]:
array1 = np.ones((4,2))
print(array1)
array1.ndim

[[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]


2

In [12]:
list1 = [10,20,30,40,50]
array1=np.array(list1)
array1.ndim

1

In [20]:
#Indexing in NumPy Array
array1=np.array([10,20,30,40,50])
print(array1[0])
print(array1[-1])

10
50


In [21]:
array1 = np.array([[10,20,30],[40,50,60],[70,80,90]])
print(array1[1,2])
print(array1[0,:])
print(array1[:,1])

60
[10 20 30]
[20 50 80]


In [22]:
#slicing in Numpy arrays
array1=np.array([10,20,30,40,50,60,70])
print(array1[1:3])
print(array1[1:6:2])
print(array1[-1:-3:-1])
print(array1[::2])
print(array1[::-1])

[20 30]
[20 40 60]
[70 60]
[10 30 50 70]
[70 60 50 40 30 20 10]


In [24]:
array1=np.array([[15,16,17],[25,26,27],[45,46,47]])
print(array1[1, ])
print(array1[:,1])
print(array1[1:3,1:3])
print(array1[1:3, ])
print(array1[:,1:3])
print(array1[1:3,1])
print(array1[1:3, :1])

[25 26 27]
[16 26 46]
[[26 27]
 [46 47]]
[[25 26 27]
 [45 46 47]]
[[16 17]
 [26 27]
 [46 47]]
[26 46]
[[25]
 [45]]


In [27]:
#Arithmetic Operations
x=np.array([[1,2],[3,4]])
y=np.array([[11,12],[13,14]])
z=x+y
print(z)
a=x-y
print(a)
b=x*y
print(b)
c=x@y
print(c)
d=y/x
print(d)
e=y//x
print(e)
f=y**x
print(f)
g=y%x
print(g)
print(x.transpose())

[[12 14]
 [16 18]]
[[-10 -10]
 [-10 -10]]
[[11 24]
 [39 56]]
[[37 40]
 [85 92]]
[[11.          6.        ]
 [ 4.33333333  3.5       ]]
[[11  6]
 [ 4  3]]
[[   11   144]
 [ 2197 38416]]
[[0 0]
 [1 2]]
[[1 3]
 [2 4]]


In [ ]:
#sorting in 2D
x=np.array([[12,11,15],[21,25,20],[18,27,16]])
y=np.sort(x,axis=0) #colunm wise sort
print(y)

[[12 11 15]
 [18 25 16]
 [21 27 20]]


In [30]:
x=np.array([[12,11,15],[21,25,20],[18,27,16]])
y=np.argsort(x,axis=1)
print(y)

[[1 0 2]
 [2 0 1]
 [2 0 1]]


In [31]:
#inplace
x=np.array([[12,11,15],[21,25,20],[18,27,16]])
x.sort()
print(x)

[[11 12 15]
 [20 21 25]
 [16 18 27]]


In [ ]:
#sorting in 1D array
x=np.array([7,2,3,9,6])
y=np.sort(x)[::-1] #for reverse
print(y)

[9 7 6 3 2]


In [35]:
x=np.array([7,2,3,9,6])
y=np.argsort(x)
print(y)

[1 2 4 0 3]


In [36]:
x=np.array([7,2,3,9,6])
x.sort()
print(x)

[2 3 6 7 9]


In [44]:
#Statistical Operations
x=np.array([4,2,3,9,7])
y=np.max(x)
a=np.min(x)
b=np.sum(x)
c=np.mean(x)
d=np.median(x)
e=np.prod(x)
f=np.var(x)
g=np.std(x)
print(y)
print(a)
print(b)
print(c)
print(d)
print(e)
print(f)
print(g)

9
2
25
5.0
4.0
1512
6.8
2.6076809620810595


In [45]:
import numpy as np

# Convert list to NumPy array
my_list = [1, 2, 3, 4]
my_array = np.array(my_list)

# Print the shape and dtype
print("Shape:", my_array.shape)
print("Data type:", my_array.dtype)

Shape: (4,)
Data type: int64


In [46]:
random_array = np.random.randint(0, 101, size=(4, 4))
print("Random 4x4 Array:\n", random_array)

Random 4x4 Array:
 [[41 41 15 65]
 [66 53 14 72]
 [92 31 69 15]
 [38 97  2 16]]


In [47]:

random_array = np.random.randint(0, 101, size=(4, 4))
print("Original 4x4 Array:\n", random_array)
middle_submatrix = random_array[1:3, 1:3]
print("\nMiddle 2x2 Sub-matrix:\n", middle_submatrix)

Original 4x4 Array:
 [[89 64 98 91]
 [16 96 64 15]
 [78 14 60 91]
 [22 55 15 57]]

Middle 2x2 Sub-matrix:
 [[96 64]
 [14 60]]


In [ ]:
# Create 1D array
array_1d = np.arange(9)




# Reshape
matrix_3x3 = array_1d.reshape(3, 3)
print("1D Array:", array_1d)
print("\nReshaped 3x3 Matrix:\n", matrix_3x3)

1D Array: [0 1 2 3 4 5 6 7 8]

Reshaped 3x3 Matrix:
 [[0 1 2]
 [3 4 5]
 [6 7 8]]
