In [2]:
import numpy as np
result=np.add.accumulate([2,3,5])
print(result)
result1=np.multiply.accumulate([2,3,5])
print(result1)

[ 2  5 10]
[ 2  6 30]


In [3]:
import numpy as np
a = np.array([1, 2, 3, 4])
b=np.negative.at(a, [0, 1])
print(a)
print(b)

[-1 -2  3  4]
None


In [4]:
a=np.multiply.outer([1, 2, 3], [4, 5, 6])
print(a)

[[ 4  5  6]
 [ 8 10 12]
 [12 15 18]]


In [5]:
a=np.multiply.reduce([2,3,5])
print(a)

30


In [9]:
a = np.add.reduceat(np.arange(8), [0, 4, 1, 5, 2, 6, 3, 7])[::2]
print(a)


[ 6 10 14 18]


In [10]:
int32 = np.dtype("int32")
float32 = np.dtype("float32")

In [12]:
a=np.add.nout
print(a)

1


In [13]:
a=np.array([1,2,3])
b=10
print(a+b)

[11 12 13]


In [14]:
a=np.ones((3,1))
b=np.array([10,20,30,40])
print(a+b)

[[11. 21. 31. 41.]
 [11. 21. 31. 41.]
 [11. 21. 31. 41.]]


In [15]:
arr=np.random.randint(0, 51, size=20)
print(arr)

[46  8  7 24 39 29  9 20  1 42 18 39 17  3 47 41 14 16 25 50]


In [16]:
arr=np.random.randint(0,51,size=20)
print("Array",arr)
print("Sum:", np.sum(arr))
print("Mean:", np.mean(arr))
print("Standard Deviation:", np.std(arr))
print("Index of Min Element (argmin):", np.argmin(arr))
print("Index of Max Element (argmax):", np.argmax(arr))

Array [28 38 20 42 40 20 43  4  0 25 21 18 33 27 49 34 11 19 20 16]
Sum: 508
Mean: 25.4
Standard Deviation: 12.760877712759417
Index of Min Element (argmin): 8
Index of Max Element (argmax): 14


In [ ]:
matrix = np.array([
    [1, 2, 3, 4],
    [5, 6, 7, 8],
    [9, 10, 11, 12]
])

vector = np.array([10, 20, 30, 40])
result = matrix + vector

print("Original matrix:\n", matrix)

print("Vector to add:\n", vector)

print("Result after broadcasting:\n", result)

Original matrix:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
Vector to add:
 [10 20 30 40]
Result after broadcasting:
 [[11 22 33 44]
 [15 26 37 48]
 [19 30 41 52]]
